# Generated by Django 4.1.7 on 2023-03-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcl',
            old_name='cloth',
            new_name='phone',
        ),
    ]
